### ISSUE TITLE
Resetting cross-endorsements or dossing between switches feels clumsy

### ISSUE THREAD

**Issue by esfalsa** [libcord-tech/gauntlet#11]
The keybinds for cross-endorsement (<kbd>Shift</kbd>+<kbd>E</kbd> by default) and for dossing nations from an activity feed (<kbd>Shift</kbd>+<kbd>D</kbd> by default) take the user through the nations they need to endorse or dossier, and the user knows when they've endorsed or dossed all the nations they need to when the keybind no longer responds to input. (Yeah...)

This feels clumsy because, among other reasons, there isn't a clear way to reset this between switching. To get an updated list of nations from the same activity feed, the fastest method feels like going back through previously visited pages (and hoping you go back the right number of pages) or just bookmarking the activity feed.

It should be possible to save the URL of the activity feed used when generating the list of nations to endorse or dossier, and send the user back to that when they're done crossing/dossing or when they press a different keybind.

**Comment by roavin** [comment]
The use-case here is for chasing, right? I'm just pondering what the "least surprising UX" is.

I intuitively find your suggestion the most sane: the final keypress simply takes the user back to the initiating page with a popup saying "All nations endorsed/dossiered" (which could be triggered by URL parameter, i.e. "gauntlet-message=all_endorsed" added to the query string).

I can imagine situations where resetting the cross state on any other keybind leads to surprises. For example, suppose you begin crossing, then remember "hey I might have updated", press U, see it's all swell, then want to continue where you left off. Clearing the state could be restricted to detecting a nation switch as well as when pressing `Shift`+`E`/`D` on an initiating page (i.e. activity feed), and in other cases it will continue where it left off.

**Comment by esfalsa** [comment]
Yeah, aside from chasing, I can't think of other use-cases right now. I
wasn't sold on the UX aspect either, though I do like the idea of a pop-up
(or perhaps just a notification so dismissing it doesn't require a
keypress). Detecting when the logged-in nation has actually changed is a
good point as well and could probably also be used to exclude the currently
logged-in nation from the list of nations to cross-endorse.
