### ISSUE TITLE
Scroll down automatically on nation pages

### ISSUE THREAD

**Issue by roavin** [libcord-tech/gauntlet#16]
I was pinged with this on Libcord:

`[6:15 PM][THA/ERN/EPSA] Vor: @[TGW] Roavin can u make gauntlet scroll down on nation pages`

I'm not entirely sure this is useful, but I wanted to note it nonetheless. Thoughts?

**Comment by paulhaku** [comment]
I don't personally find this feature useful, but this feature exists in Breeze++, so adding it may make Gauntlet feel more familiar to users migrating from Breeze++.

**Comment by roavin** [comment]
It could be bound to a setting.
