### ISSUE TITLE
Keybind for closing tabs

### ISSUE THREAD

**Issue by roavin** [libcord-tech/gauntlet#17]
Requested by Icarus:
> Is there a way that closing an NS tab is tied to one key so you dont have to reach halfway across your keyboard to press ctrl+w but instead can just press w (for example) to close the tab? It is something that ive always missed in breeze that has just improved my switch times etc a lot.

**Comment by roavin** [comment]
I think this is a good idea, but it shouldn't be set by default because that could lead to surprises.

**Comment by paulhaku** [comment]
Just from some quick googling, this doesn't seem like it's possible in Chrome due to security concerns. I'm not sure that Breeze has ever had this feature either.

**Comment by roavin** [comment]
[chrome.tabs.remove()](https://developer.chrome.com/docs/extensions/reference/tabs/#method-remove) should do the trick.
